export enum AppStep {
  UPLOAD = 0,
  DETECTION = 1,
  CONFIG = 2,
  PREVIEW = 3,
  GENERATE = 4
}

export enum FileType {
  FILE = 'file',
  FOLDER = 'folder'
}

export interface FileNode {
  id: string;
  name: string;
  type: FileType;
  content?: string; // Only for files
  language?: string;
  children?: FileNode[];
  isNew?: boolean; // For changelog visualization
}

export interface DetectionResult {
  language: string;
  framework: string;
  confidence: number;
  suggestedProjectType: string;
  detectedFiles: number;
}

export interface RepoConfig {
  name: string;
  description: string;
  author: string;
  license: string;
  projectType: string;
  framework: string;
  language: string;
  packageManager: 'npm' | 'yarn' | 'pnpm' | 'bun';
  bundler: 'vite' | 'webpack' | 'none';
  useTypeScript: boolean;
  useMonorepo: boolean;
  ciProvider: 'github' | 'gitlab' | 'none';
  includeTests: boolean;
  includeDocker: boolean;
  includeLinting: boolean;
  githubWorkflows: string[];
  githubTemplates: string[];
  githubCommunity: string[];
  githubCodeowners: boolean;
}

export const INITIAL_CONFIG: RepoConfig = {
  name: 'my-awesome-repo',
  description: 'Generated by RepoGen',
  author: 'Dev User',
  license: 'MIT',
  projectType: 'Frontend',
  framework: 'React',
  language: 'JavaScript',
  packageManager: 'npm',
  bundler: 'vite',
  useTypeScript: false,
  useMonorepo: false,
  ciProvider: 'github',
  includeTests: true,
  includeDocker: false,
  includeLinting: true,
  githubWorkflows: ['ci'],
  githubTemplates: ['bug_report', 'feature_request', 'pull_request'],
  githubCommunity: ['contributing', 'code_of_conduct'],
  githubCodeowners: true,
};

export interface GenerationLog {
  timestamp: string;
  level: 'info' | 'warn' | 'success';
  message: string;
}