export enum AppStep {
  UPLOAD = 0,
  DETECTION = 1,
  CONFIG = 2,
  PREVIEW = 3,
  GENERATE = 4
}

export enum FileType {
  FILE = 'file',
  FOLDER = 'folder'
}

export interface FileNode {
  id: string;
  name: string;
  type: FileType;
  content?: string; // Only for files
  language?: string;
  children?: FileNode[];
  isNew?: boolean; // For changelog visualization
}

export interface DetectionResult {
  language: string;
  framework: string;
  confidence: number;
  suggestedProjectType: string;
  detectedFiles: number;
}

export interface RepoConfig {
  name: string;
  description: string;
  author: string;
  license: string;
  projectType: string;
  framework: string;
  language: string;
  packageManager: 'npm' | 'yarn' | 'pnpm' | 'bun';
  bundler: 'vite' | 'webpack' | 'none';
  useTypeScript: boolean;
  useMonorepo: boolean;
  ciProvider: 'github' | 'gitlab' | 'none';
  includeTests: boolean;
  includeDocker: boolean;
  includeLinting: boolean;
  githubWorkflows: string[];
  githubTemplates: string[];
  githubCommunity: string[];
  githubCodeowners: boolean;
  ideConfig: string[];
  features: string[];
}

export const PROJECT_TYPES = [
  'Frontend Web', 'Backend API', 'Fullstack App', 'Mobile App', 'Desktop App', 'CLI Tool', 'Library/Package', 'Game', 'Data Science'
];

export const FRAMEWORKS: Record<string, string[]> = {
  'Frontend Web': ['React', 'Vue', 'Angular', 'Svelte', 'Solid', 'Preact', 'Lit', 'Alpine', 'Qwik', 'Vanilla HTML/JS'],
  'Backend API': ['Node.js (Express)', 'Node.js (NestJS)', 'Node.js (Fastify)', 'Python (Django)', 'Python (Flask)', 'Python (FastAPI)', 'Go (Gin)', 'Go (Fiber)', 'Rust (Actix)', 'Rust (Axum)', 'Java (Spring Boot)', 'C# (.NET API)'],
  'Fullstack App': ['Next.js', 'Nuxt', 'Remix', 'SvelteKit', 'Astro', 'SolidStart', 'Laravel', 'Ruby on Rails', 'Phoenix', 'Django'],
  'Mobile App': ['React Native', 'Flutter', 'Expo', 'Ionic', 'NativeScript', 'Kotlin Multiplatform'],
  'Desktop App': ['Electron', 'Tauri', 'Flutter Desktop', '.NET MAUI'],
  'CLI Tool': ['Node.js (Commander)', 'Rust (Clap)', 'Go (Cobra)', 'Python (Typer)'],
  'Library/Package': ['TypeScript (NPM)', 'Python (PyPI)', 'Rust (Crate)', 'Go (Module)'],
  'Game': ['Unity (C#)', 'Godot (GDScript)', 'Bevy (Rust)', 'Phaser (JS)'],
  'Data Science': ['Jupyter Notebook', 'Streamlit', 'Dash', 'R Shiny']
};

export const IDE_CONFIGS = [
  { id: 'vscode', label: 'VS Code (.vscode)' },
  { id: 'editorconfig', label: 'EditorConfig (.editorconfig)' },
  { id: 'idea', label: 'IntelliJ / WebStorm (.idea)' },
  { id: 'sublime', label: 'Sublime Text' },
  { id: 'devcontainer', label: 'DevContainers' },
  { id: 'gitpod', label: 'Gitpod' }
];

export const FEATURES = [
  { id: 'auth', label: 'Authentication (Auth.js / Firebase)' },
  { id: 'db', label: 'Database Setup (Prisma / Mongoose)' },
  { id: 'api', label: 'API Client (Axios / TanStack Query)' },
  { id: 'ui', label: 'UI Components (Shadcn / Tailwind)' },
  { id: 'i18n', label: 'Internationalization (i18n)' },
  { id: 'analytics', label: 'Analytics Setup' },
  { id: 'seo', label: 'SEO Optimization' },
  { id: 'pwa', label: 'PWA Support' },
  { id: 'docs', label: 'Advanced Documentation (Docs, Changelog)' }
];

export const INITIAL_CONFIG: RepoConfig = {
  name: 'my-awesome-repo',
  description: 'Generated by RepoGen',
  author: 'Dev User',
  license: 'MIT',
  projectType: 'Frontend Web',
  framework: 'React',
  language: 'TypeScript',
  packageManager: 'npm',
  bundler: 'vite',
  useTypeScript: true,
  useMonorepo: false,
  ciProvider: 'github',
  includeTests: true,
  includeDocker: false,
  includeLinting: true,
  githubWorkflows: ['ci'],
  githubTemplates: ['bug_report', 'feature_request', 'pull_request'],
  githubCommunity: ['contributing', 'code_of_conduct'],
  githubCodeowners: true,
  ideConfig: ['vscode', 'editorconfig'],
  features: []
};

export interface GenerationLog {
  timestamp: string;
  level: 'info' | 'warn' | 'success';
  message: string;
}